name: sheet_clone
description: A Flutter project
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  # Supabase
  supabase_flutter: ^2.5.4
  flutter_dotenv: ^5.1.0

  mime: any
  
  # Утилиты
  provider: ^6.1.2
  uuid: ^4.4.0
  path: ^1.9.0
  file_picker: ^8.0.0
  image_picker: ^1.1.0

  # Дата/время (эта версия совместима с Flutter 3.22+)
  intl: ^0.18.1

  # Для Web (если таргетируешь web)
  flutter_web_plugins:
    sdk: flutter
  record: ^6.1.0
  audioplayers: ^6.5.0
  url_launcher: ^6.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
