// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtk-hkhAfDwjqr4uOed_XsLGhYuh-gJjw',
    appId: '1:1066189756651:web:a7a7b78ad3dc23d49cc6ae',
    messagingSenderId: '1066189756651',
    projectId: 'sheets-40e7c',
    authDomain: 'sheets-40e7c.firebaseapp.com',
    databaseURL: 'https://sheets-40e7c-default-rtdb.firebaseio.com',
    storageBucket: 'sheets-40e7c.firebasestorage.app',
    measurementId: 'G-GJL6SBRDBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqwCu6BnKIC5jkx3HpVEDpkhJZq37cPug',
    appId: '1:1066189756651:android:2b8d5bd64e5aadc49cc6ae',
    messagingSenderId: '1066189756651',
    projectId: 'sheets-40e7c',
    databaseURL: 'https://sheets-40e7c-default-rtdb.firebaseio.com',
    storageBucket: 'sheets-40e7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL8YGQA7ibuKtHgA-EQZ7deAFynrkmzvA',
    appId: '1:1066189756651:ios:01375f3a5e9000899cc6ae',
    messagingSenderId: '1066189756651',
    projectId: 'sheets-40e7c',
    databaseURL: 'https://sheets-40e7c-default-rtdb.firebaseio.com',
    storageBucket: 'sheets-40e7c.firebasestorage.app',
    iosBundleId: 'com.example.sheetClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL8YGQA7ibuKtHgA-EQZ7deAFynrkmzvA',
    appId: '1:1066189756651:ios:01375f3a5e9000899cc6ae',
    messagingSenderId: '1066189756651',
    projectId: 'sheets-40e7c',
    databaseURL: 'https://sheets-40e7c-default-rtdb.firebaseio.com',
    storageBucket: 'sheets-40e7c.firebasestorage.app',
    iosBundleId: 'com.example.sheetClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtk-hkhAfDwjqr4uOed_XsLGhYuh-gJjw',
    appId: '1:1066189756651:web:d01f8e55a08604599cc6ae',
    messagingSenderId: '1066189756651',
    projectId: 'sheets-40e7c',
    authDomain: 'sheets-40e7c.firebaseapp.com',
    databaseURL: 'https://sheets-40e7c-default-rtdb.firebaseio.com',
    storageBucket: 'sheets-40e7c.firebasestorage.app',
    measurementId: 'G-QH4T1DLTBS',
  );
}
