begin;

insert into public.ai_entities
  (code, business_name, entity_kind, source_schema, source_object, description, sensitivity)
values
  ('order', 'Заказ', 'table', 'public', 'orders', 'Заказ имеет поколения; наивный count(*) может задвоить возобновлённые заказы.', 'internal'),
  ('task', 'Производственная задача', 'table', 'public', 'tasks', 'Задача и JSONB-журнал производственных событий в comments.', 'internal'),
  ('stage', 'Этап производства', 'concept', 'public', null, 'Логический этап маршрута; может объединять несколько рабочих мест.', 'internal'),
  ('workplace', 'Рабочее место', 'table', 'public', 'workplaces', 'Источник тиража этапа и производственной скорости.', 'internal'),
  ('employee', 'Сотрудник', 'table', 'public', 'employees', 'Участник производства; персональные и финансовые поля ограничены.', 'personal'),
  ('paint', 'Краска', 'table', 'public', 'paints', 'Складская краска, брони, списания и неприкасаемый запас.', 'internal'),
  ('paper', 'Бумага', 'table', 'public', 'papers', 'Складская бумага, резервы, списания и расход по этапам.', 'internal'),
  ('shipment', 'Отгрузка', 'table', 'public', 'order_shipments', 'Партия отгрузки; сумма партий определяет отгруженное количество.', 'internal'),
  ('product_type_config', 'Версия маршрута типа продукта', 'table', 'public', 'product_type_configs', 'Черновики и опубликованные версии маршрутов нельзя смешивать.', 'internal')
on conflict (code) do update set
  business_name = excluded.business_name,
  entity_kind = excluded.entity_kind,
  source_schema = excluded.source_schema,
  source_object = excluded.source_object,
  description = excluded.description,
  sensitivity = excluded.sensitivity,
  updated_at = now();

insert into public.ai_business_rules
  (code, title, rule_text, enforcement_layer, severity, entity_codes, source_references, confirmed_by_human, metadata)
values
  ('TRAP-01', 'Выработка хранится в JSONB-журнале',
   'Выработка, время, зарплата и КПД считаются только по утверждённым золотым запросам, повторяющим TaskAnalyticsMapper. Свободная агрегация tasks.comments запрещена.',
   'dart', 'critical', array['task','employee','workplace'],
   array['lib/modules/analytics/repositories/task_analytics_mapper.dart'], true,
   '{"requires_golden_query":true,"event_types":["time_event","quantity_stage_total","quantity_done","quantity_team_total","quantity_share","setup_done"]}'),
  ('TRAP-02', 'Личное количество не равно тиражу этапа',
   'quantity_stage_total принадлежит рабочему месту. Сумма quantity_done по бригаде может завысить тираж и не используется как тираж этапа.',
   'dart', 'critical', array['task','employee','workplace'],
   array['lib/modules/analytics/repositories/task_analytics_mapper.dart'], true,
   '{"requires_golden_query":true}'),
  ('TRAP-03', 'Исторические артефакты долей',
   'quantity_share на старых периодах может содержать фантомные или потерянные доли. Находка должна учитывать дату соответствующей миграции и отличать текущий дефект от исторического артефакта.',
   'mixed', 'high', array['task','employee'],
   array['supabase/migrations/20260821_quantity_share_by_time.sql','supabase/migrations/20260908_backfill_quantity_shares.sql','supabase/migrations/20260914_integrity_3_personal_shares.sql'], true,
   '{"requires_golden_query":true}'),
  ('TRAP-04', 'Бизнес-время Костаная',
   'Относительные периоды считаются в часовом поясе Костаная UTC+5. План без явной нормализации периода отклоняется.',
   'agent', 'critical', array['order','task'],
   array['lib/utils/kostanay_time.dart'], true,
   '{"timezone":"Asia/Qostanay","utc_offset":"+05:00","requires_time_normalization":true}'),
  ('TRAP-05', 'Поколения заказа считаются одной цепочкой',
   'Возобновлённые поколения заказа склеиваются по утверждённому правилу. Наивный count(*) из orders запрещён для подсчёта бизнес-заказов.',
   'mixed', 'critical', array['order'],
   array['lib/modules/orders/order_generation_switcher.dart'], true,
   '{"requires_golden_query":true}'),
  ('TRAP-06', 'Производственное завершение и отгрузка различаются',
   'Завершение производства, orders.completed_at, orders.shipped_at и строки order_shipments имеют разные смыслы. Остаток отгрузки вычисляется как фактическое количество минус сумма партий.',
   'mixed', 'high', array['order','shipment'],
   array['lib/modules/orders/order_shipment_rules.dart','supabase/migrations/20260910_order_shipments.sql'], true,
   '{"requires_golden_query":true}'),
  ('TRAP-07', 'Часть инвариантов существует только в Dart',
   'Правила запуска, формы, расхода бумаги, брони краски и отгрузки должны быть перенесены в каталог с признаком enforcement_layer=dart.',
   'dart', 'high', array['order','paper','paint','shipment'],
   array['lib/modules/orders/order_launch_rules.dart','lib/modules/orders/order_form_rules.dart','lib/modules/orders/paper_usage_rules.dart','lib/modules/orders/paint_reservation_rules.dart','lib/modules/orders/order_shipment_rules.dart'], true,
   '{}'),
  ('TRAP-08', 'RLS не разделяет сотрудников',
   'Общий auth-пользователь приложения означает, что RLS не является границей прав агента или людей. Ограничения агента задаются отдельным read-only доступом и шлюзом.',
   'database', 'critical', array['employee'],
   array['docs/ai_db_agent_spec.md#3.8'], true,
   '{}'),
  ('TRAP-09', 'Готовая диагностика является базовой',
   'Новые проверки расширяют public.data_health_report() и ссылаются на существующий код проверки, если смысл совпадает.',
   'database', 'high', array['task','paint'],
   array['supabase/migrations/20260914_integrity_4_data_health_report.sql'], true,
   '{"function":"public.data_health_report"}'),
  ('TRAP-10', 'Дрейф схемы сверяется с журналом',
   'Снимки структуры сравниваются с public.schema_change_log. Изменённая зависимость блокирует затронутый золотой запрос до проверки человеком.',
   'database', 'high', array[]::text[],
   array['supabase/migrations/20260914_integrity_13_schema_change_log.sql'], true,
   '{"table":"public.schema_change_log"}'),
  ('TRAP-11', 'Маршруты имеют версии',
   'Вопрос о маршруте обязан различать draft, published и archived. Проверки настроек выполняются по черновикам, производственные ответы — по явно выбранной версии.',
   'mixed', 'high', array['product_type_config','stage','workplace'],
   array['lib/modules/orders/product_type_route.dart','lib/modules/orders/product_type_stage_guards.dart'], true,
   '{}'),
  ('TRAP-12', 'Секретный ключ не принадлежит агенту',
   'Агент основной базы не получает service_role или другой ключ с правом записи. Секреты и хэши никогда не выбираются и не помещаются в каталог.',
   'agent', 'critical', array['employee'],
   array['docs/ai_db_agent_spec.md#3.12'], true,
   '{"forbidden_objects":["public.employee_password_hashes"]}')
on conflict (code) do update set
  title = excluded.title,
  rule_text = excluded.rule_text,
  enforcement_layer = excluded.enforcement_layer,
  severity = excluded.severity,
  entity_codes = excluded.entity_codes,
  source_references = excluded.source_references,
  confirmed_by_human = excluded.confirmed_by_human,
  metadata = excluded.metadata,
  updated_at = now();

insert into public.ai_terms
  (term, aliases, entity_codes, definition, source_reference, confirmed_by_human)
values
  ('тираж этапа', array['тираж','объём этапа','stage total'], array['task','workplace'],
   'Общее количество этапа на рабочем месте из quantity_stage_total; не сумма личных количеств.',
   'lib/modules/analytics/repositories/task_analytics_mapper.dart', true),
  ('личная выработка', array['выработка сотрудника','личное количество'], array['task','employee'],
   'Количество сотрудника из quantity_done, quantity_team_total или quantity_share по правилам TaskAnalyticsMapper.',
   'lib/modules/analytics/repositories/task_analytics_mapper.dart', true),
  ('приладка', array['настройка','наладка','setup'], array['task','employee','workplace'],
   'Наладка этапа. Оплачивается первому основному исполнителю, начавшему setup-интервал; помощник не считается первым наладчиком.',
   'lib/modules/analytics/repositories/task_analytics_mapper.dart', true),
  ('пересмена', array['смена исполнителя','shift change'], array['task','employee'],
   'Смена участника в ходе задачи; количество может распределяться через quantity_share.',
   'lib/modules/analytics/repositories/task_analytics_mapper.dart', true),
  ('переходящая краска', array['перенос краски','краска между заказами'], array['paint','order'],
   'Бронь краски, связанная с последующим заказом и отложенными списаниями; неприкасаемый запас не вычитается повторно.',
   'lib/modules/orders/paint_reservation_rules.dart', true),
  ('бизнес-день', array['сегодня','день производства'], array['order','task'],
   'Календарный период в часовом поясе Костаная UTC+5, включая корректную обработку ночных смен.',
   'lib/utils/kostanay_time.dart', true),
  ('поколение заказа', array['возобновление заказа','цепочка заказа'], array['order'],
   'Одна версия заказа в цепочке возобновлений; бизнес-подсчёт выполняется по цепочке, а не по строкам.',
   'lib/modules/orders/order_generation_switcher.dart', true)
on conflict (term) do update set
  aliases = excluded.aliases,
  entity_codes = excluded.entity_codes,
  definition = excluded.definition,
  source_reference = excluded.source_reference,
  confirmed_by_human = excluded.confirmed_by_human,
  updated_at = now();

commit;
